# Generated by Django 3.1.7 on 2021-03-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(default=None, max_length=200, null=True)),
                ('comercial', models.CharField(default=None, max_length=200, null=True)),
                ('DNI', models.CharField(default=None, max_length=50, null=True)),
                ('CP', models.CharField(default=None, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('origen', models.CharField(choices=[('Cliente referenciado', 'Cliente referenciado'), ('Cliente de tienda', 'Cliente de tienda'), ('Cliente de cartera', 'Cliente de cartera')], default='Cliente referenciado', max_length=50)),
                ('fecha_contacto', models.DateField(blank=True, default=None, null=True)),
                ('fecha_venta', models.DateField(blank=True, default=None, null=True)),
                ('fecha_agendado', models.DateField(blank=True, default=None, null=True)),
                ('segmento', models.CharField(choices=[('Particular', 'Particular'), ('Autónomo', 'Autónomo'), ('Empresa', 'Empresa')], default=None, max_length=50, null=True)),
                ('movil', models.CharField(default=None, max_length=9, null=True)),
                ('fijo', models.CharField(blank=True, default=None, max_length=9, null=True)),
                ('operador', models.CharField(choices=[('Yoigo', 'Yoigo'), ('Movistar', 'Movistar'), ('Vodafone', 'Vodafone'), ('Orange', 'Orange'), ('Digi', 'Digi'), ('Lowi', 'Lowi'), ('Jazztel', 'Jazztel'), ('Grupo MasMovil', 'Grupo MasMovil'), ('Otros', 'Otros')], default=None, max_length=40, null=True)),
                ('estado', models.CharField(choices=[('Llamado', 'Llamado'), ('Ofertado', 'Ofertado'), ('Agendado', 'Agendado'), ('No contesta', 'No contesta'), ('No interesa', 'No interesa'), ('Vendido', 'Vendido'), ('No existe', 'No existe')], default=None, max_length=20, null=True)),
                ('motivo_no_interesa', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('notas', models.CharField(blank=True, default=None, max_length=1100, null=True)),
                ('FMC_porta_FIJO', models.IntegerField(default=None, null=True)),
                ('FMC_Fijo_Nuevo', models.IntegerField(default=None, null=True)),
                ('POSPAGO_MO', models.IntegerField(default=None, null=True)),
                ('POSPAGO_MB_DUO_MB', models.IntegerField(default=None, null=True)),
                ('CROSS_Fijo_Portado', models.IntegerField(default=None, null=True)),
                ('CROSS_Fijo_Nuevo', models.IntegerField(default=None, null=True)),
                ('RENUEVO', models.IntegerField(default=None, null=True)),
                ('RENUEVO_CON_SUBIDA', models.IntegerField(default=None, null=True)),
                ('TV', models.IntegerField(default=None, null=True)),
                ('SEGURO', models.IntegerField(default=None, null=True)),
                ('ACCESORIOS', models.IntegerField(default=None, null=True)),
                ('TERMINAL_LIBRE', models.IntegerField(default=None, null=True)),
                ('CAMBIO_TECNOLOGIA', models.IntegerField(default=None, null=True)),
                ('PREPAGO', models.IntegerField(default=None, null=True)),
                ('SEGURO_FAMILIA', models.IntegerField(default=None, null=True)),
                ('PEPENERGY', models.IntegerField(default=None, null=True)),
                ('ENERGY_GO', models.IntegerField(default=None, null=True)),
                ('SMART_HOME', models.IntegerField(default=None, null=True)),
                ('MO_ADICIONAL', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
