# Generated by Django 3.1.7 on 2021-03-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmasgestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(choices=[('Llamado', 'Llamado'), ('Ofertado', 'Ofertado'), ('Agendado', 'Agendado'), ('No contesta', 'No contesta'), ('No interesa', 'No interesa'), ('Vendido', 'Vendido'), ('No existe', 'No existe')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fijo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='movil',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
